### ISSUE TITLE
Feature Request: List today's tasks

### ISSUE THREAD

**Issue by douglance** [moranje/alfred-workflow-todoist#1]
I love the workflow. It's awesome. I would like to be able to see today's tasks when I type "todo" or hit the hotkey I set up. It'd it super convenient to list them there! Thanks for a great workflow!

**Comment by moranje** [comment]
Hmmm interesting idea, I would have to read up on the Alfred documentation to see how to present multiple options in the dropdown menu.

**Comment by douglance** [comment]
Check out https://github.com/fspinillo/slackfred for a workflow that does a similar thing (list objects using an API).

**Comment by moranje** [comment]
@douglance I have a present for you :)

**Comment by douglance** [comment]
I'm trying to get it to work but it's not working for me! I'm not sure where to put the API key in the osascript. I'm on the latest El Capitan.

**Comment by douglance** [comment]
Oh snap! I found it. That is awesome!

**Comment by moranje** [comment]
Great I'm glad you like it :)
