### ISSUE TITLE
Fresh workflow installation doesn't work

### ISSUE THREAD

**Issue by robinandersson** [moranje/alfred-workflow-todoist#109]
### Description

After downloading and installing the workflow none of it's related commands are able to receive/process arguments (reverts to Alfred default fallbacks instead).

Similar to #51.

### Steps to reproduce

1. Download workflow.
2. Bring up Alfred input field
3. Partially type keyword ("todos", "todo" or "todo:setting") – Alfred shows the workflow's keyword(s) with hints
4. Complete keyword and input blank space – Alfred reverts to default fallback (in my case, google-search for whole string).

### Expected behavior

Show and/or process arguments sent with accompanying keyword (i.e. don't revert to fallbacks).

### Error logs

Log:

```
[2019-04-01 15:59:24][input.scriptfilter] Queuing argument ''
[2019-04-01 15:59:25][input.scriptfilter] Script with argument '(null)' finished
[2019-04-01 15:59:25][ERROR: input.scriptfilter] Code 1: /Users/{user}/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.6D16C36E-4027-4481-80E6-E881A238C69B/alfred-workflow-todoist.js:39440
    var timePassed = new Date().getTime() - new Date(FILES.workflowConfig.updated).getTime();
                                                                          ^

TypeError: Cannot read property 'updated' of undefined
    at Object.updateWorkflowVersion (/Users/{user}/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.6D16C36E-4027-4481-80E6-E881A238C69B/alfred-workflow-todoist.js:39440:83)

...
```
Note: replaced username with "{user}" in logs.

### Additional context

I use a symlink in /usr/local/bin to reference current nvm version of node (without it I get the error logging "You need to have node (8.5 or up) installed").

Thanks in advance!

**Comment by moranje** [comment]
I'm not entirely sure why you (;-)) broke the workflow. I can't reproduce the error you are getting. I have a feeling that:

```js
process.cwd()
```

Doesn't point to the workflow root for some reason. Let's test that assumption. I have build you a custom version. Would you mind running that to see if that yields any clues? For Alfred to recognize the worflow, the extension must be changes from `.zip` to `.alfredworkflow`.

[Alfred Workflow Todoist.zip](https://github.com/moranje/alfred-workflow-todoist/files/3031086/Alfred.Workflow.Todoist.zip)

**Comment by robinandersson** [comment]
Hehe yeah that's what I do, I break things 😉.

Alright, I have no experience developing Alfred workflows myself, so you'll have to be the coordinator ^^ I did try out some different node versions though, but with same results.

I'll just post most of the logs here for you to delve into 😄 

```
[2019-04-02 11:13:12][ERROR: input.scriptfilter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
{user}s Error:

Expected workflow root: /Users/{user}/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.7F34FBAE-89E1-4979-80A3-3BF4AB9AD14C
{"cache":[]}
TypeError: Cannot read property 'updated' of undefined

ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS 10.14.3
query: 
node.js: v11.6.0
alfred: 3.8.1
workflow: 5.8.1-debug.1
Stack: TypeError: Cannot read property 'updated' of undefined
    at Object.updateWorkflowVersion (/Users/{user}/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.7F34FBAE-89E1-4979-80A3-3BF4AB9AD14C/alfred-workflow-todoist.js:39532:83)
    at Object.<anonymous> (/Users/{user}/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.7F34FBAE-89E1-4979-80A3-3BF4AB9AD14C/alfred-workflow-todoist.js:39586:13)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    
    ...
    
{"items":[{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"SETTING: token","subtitle":"Must be a valid todoist token (40 chars and only 0-9 and a-f)","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":" token"},{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"SETTING: language","subtitle":"Must be one of: en, da, pl, zh, ko, de, pt, ja, it, fr, sv, ru, es, nl","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":" language"},{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"SETTING: max_items","subtitle":"Must be a number between 1 and 20","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":" max_items"},{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"SETTING: cache_timeout","subtitle":"Must be a number between 1 and 604800","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":" cache_timeout"},{"uid":"693e9af84d3dfcc71e640e005bdc5e2e","title":"SETTING: anonymous_statistics","subtitle":"Can either be true of false","icon":{"path":"icon.png"},"type":"default","valid":false,"autocomplete":" anonymous_statistics"}]}
```

**Comment by imagesafari** [comment]
It isn't working for me either, fwiw.

**Comment by moranje** [comment]
I'll see what I can do to run this on a fresh machine tomorrow. Thanks for reporting.

**Comment by taylorjdawson** [comment]
I was experience the exact same issue and can confirm that the debug works for me. Thanks! 👍

**Comment by moranje** [comment]
@taylorjdawson thanks that helps. @robinandersson maybe you could have a look so i can release a patch?

**Comment by taylorjdawson** [comment]
Curious as to what the fix was?

I was looking [here](https://github.com/moranje/alfred-workflow-todoist/blob/236a369867c1d4ff4e5825c759e3fd1ce6032c4b/src/project/files.ts#L9-L15) and it seems like it would be beneficial to describe the error in this code block? 
```
try {
  settings = require(SETTINGS_PATH)
  cache = require(CACHE_PATH)
  workflowConfig = require(WORKFLOW_JSON)
} catch (err) {
  // Do nothing
}
```
Then you could know which `require` statement breaks.

**Comment by robinandersson** [comment]
Hey, sorry for late reply @moranje, just tried that new build and it works! 🙂

Great work 🌈👍

**Comment by imagesafari** [comment]
Debug build works for me.

**Comment by moranje** [comment]
Thanks for the feedback guys! The problem was that error block, two of the three statements are expected to fail sometimes but the last one should never. So if you don't have a settings or cache file yet it fails and that's ok. But because they're all in the same error block that means when that happens the third file is never loaded. I have separated each statement in a separate error block now.

**Comment by taylorjdawson** [comment]
Thanks @moranje for your work!!

**Comment by andykenward** [comment]
On a fresh install of 5.8.1 when trying to set the API Token using `todo:setting` I get the fallback search. So unable to set a API Token. Even when adding `todo:setting token`

**Comment by andykenward** [comment]
Might have to do with that I have node `v10.15.3` as my default version via NVM. Looking into it.

**Comment by moranje** [comment]
Keep me in the loop. Also a new issue would probably be the best way to
track the issue.

Martien

Op ma 8 apr. 2019 18:45 schreef Andy Kenward <notifications@github.com>:

**Comment by andykenward** [comment]
@moranje No need for a new issue. Was the usage of nvm for node management. Relates to https://github.com/moranje/alfred-workflow-todoist/issues/61 . Solved it by editing the scripts in the workflow to point to nvm for node instead of `PATH=$PATH:/usr/local/bin:/usr/bin`.

**Comment by robinandersson** [comment]
You know, it wouldn't be a bad idea to put suggestions on how to what @andykenward did in the readme. Or if we (well you @moranje xD) are being super serious, perhaps even catch the node-error and display an appropriate error message since it's surely a common error (many probably doesn't read the readme).

Before I realized there was/is a debug-mode for Alfred I was convinced it was my nvm-node setup that was the culprit since the outcome were the same (i.e. reverting to default fallbacks) even when I fixed the path error. I gave up on this workflow a few months ago, and almost did the same this time but decided to post an issue about it instead since I need this in my life.😅

**Comment by andykenward** [comment]
@robinandersson my workaround will get replaced on an update to the workflow. So not sure it's the best option. 

I agree with showing the node error to the user. Without the debug option in Alfred showing the issue to me I would have given up.

Currently I don't use this workflow and instead run the Todoist mac app. Then I've made my own workflow for the Alfred keyword `todo` to the key combo `^⌘A`. Which brings up the Todoist app dialog. 

![Screenshot 2019-04-10 at 17 32 10](https://user-images.githubusercontent.com/4893048/55896614-9f854e80-5bb6-11e9-8aef-d4b9fe1b34bd.png)

**Comment by moranje** [comment]
Would any of you be willing to submit a pull request to the docs explaining
what you did?

Op wo 10 apr. 2019 18:34 schreef Andy Kenward <notifications@github.com>:

**Comment by robinandersson** [comment]
Yeah that's true what you said about needing to update the workflow manually for each release @andykenward. I believe creating a symlink in /usr/local/bin that points to an nvm version of node should work, as long as you don't remove that node version of course (switching active node version in nvm should be fine).

@moranje, I can submit a pull request. I could propose both solutions – from me and the one from @andykenward if you want.

Although it does feel like this problem should have trivial solution to be put in the workflow itself, right? 😅 I mean it's even frustrating, even to me, that we can't seem to figure out how to do it pragmatically 😆

**Comment by moranje** [comment]
I'd be open to something in the workflow as well but I don't use nvm
myself. If you can come up with a a solution for the workflow, even better.

Martien

Op do 11 apr. 2019 20:05 schreef Robin Andersson <notifications@github.com>:

**Comment by robinandersson** [comment]
@moranje, unfortunately I don't have time at the moment to get into bash scripts. But I'll do the pull request for the readme, no problem ☀️👍
