### ISSUE TITLE
Packal Source

### ISSUE THREAD

**Issue by WillPlatnick** [moranje/alfred-workflow-todoist#11]
When you download from packal, even though it says it's downloading the 3.1.1 release on the web site, what is actually downloaded isn't 3.1.1 in Alfred, as it didn't have your PATH changes in calls.js. I had to put those in manually, and also this one https://github.com/moranje/alfred-workflow-todoist/pull/9

**Comment by moranje** [comment]
I've updated the binary both on packal as well as on github. Can you verify that this fixes your problem?

**Comment by WillPlatnick** [comment]
👍
