### ISSUE TITLE
API v8 beta is being deprecated in August 30. Tests not working for rest/v1

### ISSUE THREAD

**Issue by primeminister** [moranje/alfred-workflow-todoist#113]
Hi,
I tried to update the uri in [here](https://github.com/moranje/alfred-workflow-todoist/blob/master/src/todoist/rest-api-v8.ts) to _https://api.todoist.com/rest/v1_ but all the tests fail when I run ```npm run test```. Don't know how to fix that :(

**Comment by moranje** [comment]
Something needs fixing. Thanks for pointing out the deprecation notice.

**Comment by primeminister** [comment]
Nice!!
