### ISSUE TITLE
Other projects listed

### ISSUE THREAD

**Issue by mauricerenck** [moranje/alfred-workflow-todoist#117]
After not using the workflow for quite some time, I just wanted to add a new Task to a project using the old workflow. But the projects listed aren't mine! In the app there are to correct projects. I don't know if this is an issue with the workflow (having a wrong user set anywhere?) or if this is a major issue with Todist itself. 

Running Alfred 4.03, Workflow 4.0.2

![todoist-alfred](https://user-images.githubusercontent.com/964547/64472686-89c68600-d162-11e9-90ad-dfc2ae2b3d41.png)

**Comment by moranje** [comment]
I do recognize these projects ;-). My best guess would be that you received my cache somewhere, these listed projects may come from there. I would recommend upgrading the workflow though, the version of the REST API in the workflow you are using is being deprecated by Todoist. The latest version fixes that, be aware that you need to upgrade your node version as well (at least 11.5).

Let me know if you still have problem after that.

Martien

**Comment by mauricerenck** [comment]
Well, I added you some todos ;)
Thanks for letting me know. I just updated the workflow and your projects are gone.

Have a nice weekend.
Maurice
