### ISSUE TITLE
Support for nested projects

### ISSUE THREAD

**Issue by johin** [moranje/alfred-workflow-todoist#12]
Getting an error when passing a nested project name.

**Comment by moranje** [comment]
Hi! If your nested project has a unique name, just use the name of the name the deepest nested project. There is a problem for which I don't have a solution at the moment for duplicate project names. There is no way to know which of the projects are nested under which parent from the information I get from the API. Btw project names are allowed to have `/` in their names so it wouldn't be possible to use slashes to select a nested project even if I were to solve the parent-child relationship. For now, the only solution is to create unique project names.

```json
{
            "name": "Work",
            "color": 18,
            "is_deleted": 0,
            "collapsed": 0,
            "id": 152482484,
            "parent_id": null,
            "item_order": 6,
            "indent": 1,
            "shared": false,
            "is_archived": 0
 }
```
