### ISSUE TITLE
Latest version looks like it don't accept arguments (still on Alfred 3)

### ISSUE THREAD

**Issue by mvaneijgen** [moranje/alfred-workflow-todoist#121]
# v5.8.3
[![https://www.youtube.com/watch?v=EtYYfiWiiKg](https://img.youtube.com/vi/EtYYfiWiiKg/0.jpg)](https://www.youtube.com/watch?v=https://www.youtube.com/watch?v=EtYYfiWiiKg)

# v5.8.2 
[![https://www.youtube.com/watch?v=nO6qfPixvuc](https://img.youtube.com/vi/nO6qfPixvuc/0.jpg)](https://www.youtube.com/watch?v=https://www.youtube.com/watch?v=nO6qfPixvuc)

### Description

I've not yet updated to Alfred 4 and still on 3. I have a few todoist tools running on the API myself and suddenly they all broke. I've moved them all the to stable v1 from v8 (the logic on moving backwards in version numbering is lost on me...), but with this I also needed to update my Alfred todoist workflow. When updating I lost the ability to insert arguments, if I do it will search google with the argument I've typed in. 

I've got it working again by moving down a version (v5.8.2) and changing line `37466` of `alfred-workflow-todoist.js` to the following 

```
var type = _a.type, _b = _a.uri, uri = _b === void 0 ? 'https://api.todoist.com/rest/v1/' : _b, token = _a.token;
```

From

```
var type = _a.type, _b = _a.uri, uri = _b === void 0 ? 'https://beta.todoist.com/API/v8' : _b, token = _a.token;
```

Which works for me. 

Log:

```
ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS 10.14.6 (18G95)
node.js: v10.16.0
alfred: v3.8.4
workflow: v5.8.3
```

**Comment by bumpux** [comment]
Not working, per other threads. Followed all config instructions for NVM etc. Assume this is owing to incompatibility with Alfred 4.
<img width="320" alt="Banners and Alerts 2019-10-16 08-42-57" src="https://user-images.githubusercontent.com/947598/66935535-0154c400-eff1-11e9-9c8d-3ab0cfb2c0b2.png">

**Comment by moranje** [comment]
This means you don't have the latest version of the workflow. Todoist deprecated their beta API, but the latest version of the workflow has you covered.

**Comment by mvaneijgen** [comment]
@moranje sorry maybe it was not clear. I can't create todo's on the latest version (v5.8.3) the workflow is for some reason not accepting arguments, so I have to revert back to version v5.8.2 and change the API URL

# v5.8.3
[![https://www.youtube.com/watch?v=EtYYfiWiiKg](https://img.youtube.com/vi/https://www.youtube.com/watch?v=EtYYfiWiiKg/0.jpg)](https://www.youtube.com/watch?v=https://www.youtube.com/watch?v=EtYYfiWiiKg)

# v5.8.2 
[![https://www.youtube.com/watch?v=nO6qfPixvuc](https://img.youtube.com/vi/https://www.youtube.com/watch?v=nO6qfPixvuc/0.jpg)](https://www.youtube.com/watch?v=https://www.youtube.com/watch?v=nO6qfPixvuc)[!

**Comment by moranje** [comment]
Ah sorry, I misunderstood. I see you are on node 10.x, which isn't supported by the latest workflow. I can't be sure without logs though, but it's a problem that's been reported before.

**Comment by mvaneijgen** [comment]
if node `10.x` isn't supported what version is?

Here is the log of version 5.8.3 https://gist.github.com/mvaneijgen/f297c9465bcbe5f90f947bfed5f87f08

**Comment by moranje** [comment]
12.x for the support of web workers.
