### ISSUE TITLE
Notifications not showing in Alfred v4

### ISSUE THREAD

**Issue by stacksjb** [moranje/alfred-workflow-todoist#125]
After creating a task using this, I expect to receive some sort of notification that task creation was successful or failed.

Upon creation of a task, I do not get any notification. I am on Mac OS X 10.15 (Catalina), Alfred 4.0.7[1128], and v5.8.3 of todoist workflow.

I have tested the following:
1) Downloading older versions of Todoist workflow plugin. Versions prior to 5.8.x (5.7.1 and older) successfully created a notification (though obviously task creation fails due to the new API). 5.8.0 and newer do not create an alert.
2) Manually initiating the notification by navigating to the directory "/Alfred/Alfred.alfredpreferences/workflows/user.workflow.EEB9661C-EE43-4BC7-9415-5A6B3C55C196/notifier/terminal-notifier.app/Contents/MacOS/" and executing ./terminal-notifier -message TEST - alert notification appeared successfully.

I have manually worked around the issue by adding a "Post Notification" action to the workflow as a followup step in Alfred, which works but isn't ideal as it doesn't return the full responses (but it does at least let me see if it is successful or fails.

**Comment by stacksjb** [comment]
Did anything change between version 5.7 and 5.8 in terms of notifications?

I suspect this is something to do with Catalina and either notification permissions or security restrictions to launching untrusted applications (since an older version works successfully, it would have been whitelisted if it was present prior to upgrade). That said, I have tried launching the notifier app manually (where I did get a security notification, but that went away after I allowed it to launch), and the notifier binary (and Alfred) are listed as allowing notifications.

I tested an updated version of the terminal-notifier from https://github.com/julienXX/terminal-notifier but had the same issue.

**Comment by moranje** [comment]
Looking back at the changes I think a hard-coded reference to Alfred V3 may be what's going awry.

https://github.com/moranje/alfred-workflow-todoist/blob/master/src/workflow/notification.ts#L66

Let's see if there is a way to get this information dynamically.

**Comment by moranje** [comment]
@stacksjb I may have a fix, not sure because I'm not on Alfred 4 myself yet. Can you give it a go? Here's a beta of the worflow, replace `.zip` with `.alfredworkflow`.

[Alfred Workflow Todoist.zip](https://github.com/moranje/alfred-workflow-todoist/files/3902539/Alfred.Workflow.Todoist.zip)

**Comment by stacksjb** [comment]
That one works!

It would be nice if it showed the actual task created or completed (by title) if that was possible, but this matches the previous functionality. 

Thx!

**Comment by moranje** [comment]
Great! Thanks for testing. Hehe, you keep me busy. I'll have a go at the other issues first.
