### ISSUE TITLE
Project labels aren't being added to the task

### ISSUE THREAD

**Issue by superradian** [moranje/alfred-workflow-todoist#14]
Thank you for this extension, it's been incredible and I'm loving it so far! I ran into an issue last night where for some reason, adding my project labels don't work anymore and they all go to my inbox. I've tried capitalizing and adding hashtags to no avail.

Does your extension support Sub-Projects? I made a new test folder without sub-projects to test, but it still failed. I did add sub-projects for the first time last night though, so I'm wondering if it was a trigger somehow.

**Comment by superradian** [comment]
Actually, now the extension isn't working at all. I'll get a notification that it was successfully added, but all I'll have is a blank task in the app. The only thing that loads is the due date, but not the task or the project.

**Comment by moranje** [comment]
I will try to look into it when I have some time.

Op ma 12 dec. 2016 16:48 schreef superradian <notifications@github.com>:

**Comment by stacksjb** [comment]
I found it works using the todo {task},{date},{project} format for me.

Ideally I'd like to add tasks using the same natural language as in todoist, with # for project. For example, todoist takes this:

Finish report #work p2 ev jan 3 (goes to work project with priority 2 due every jan 3)..

**Comment by bfolberth** [comment]
@stacksjb +1

**Comment by moranje** [comment]
I will look into parsing `#project`, however I see no easy way to differentiate between task text and date text so a separator will still be required there.

**Comment by moranje** [comment]
I have prepared a beta version that does just this. Also added some sugar for selecting projects and labels. Let me know if this is what you meant.

[Alfred Workflow Todoist.alfredworkflow.zip](https://github.com/moranje/alfred-workflow-todoist/files/1058873/Alfred.Workflow.Todoist.alfredworkflow.zip)
