### ISSUE TITLE
Show Due Dates in `todos`

### ISSUE THREAD

**Issue by novotnyr** [moranje/alfred-workflow-todoist#15]
It would be nice to show Due Dates in `todos` command.

Generally, each item from [Alfred API](https://developer.todoist.com/#items) contains either the `date_string` (natural language format) or `due_date_utc` date. UTC date can be processed and shown in the Alfred item content.

**Comment by moranje** [comment]
Maybe I am mistaken but there doesn't seem to be a `date_string` in the alfred API, perhaps you meant the one in the Todoist API? 

What would you like the format the be like `[date_string]: Get the broccoli`?

**Comment by novotnyr** [comment]
My bad, it is indeed in the Todoist API. 

In my local setup, I am using `Get the broccoli: ([date_string])`.

<img width="578" alt="todoist-alfred" src="https://cloud.githubusercontent.com/assets/1109928/26529012/19dc47a6-43b8-11e7-96df-750ccb5adcb6.png">

**Comment by moranje** [comment]
This has been added to the latest release
