### ISSUE TITLE
[Bug] TypeError: Expected a JSON string, got '{"name": "read", "args": "\\"today\\""}' (string)

### ISSUE THREAD

**Issue by wesleylancel** [moranje/alfred-workflow-todoist#159]
### Description

Not sure if it's supposed to work in the latest alpha yet, but was testing filtering by Todoist.

### Steps to reproduce behavior

Using query `todos "today"`.

### Expected behavior

Return tasks due today.

### Error logs

ALFRED WORKFLOW TODOIST
----------------------------------------
_Title_: TypeError
_Description_: Expected a JSON string, got '{"name": "read", "args": "\\"today\\""}' (string)

_OS_: macOS 10.15.2
_Query_: <unknown>
_Node.js_: v13.8.0
_Alfred_: 4.0.8
_Workflow_: 6.0.0-alpha.9
_Workflow-id_: user.workflow.3A552C27-FCF3-47A7-8524-C8C6FE4B26FA

_Stack_: TypeError: Expected a JSON string, got '{"name": "read", "args": "//"today//""}' (string)
    at I ([snip]/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A552C27-FCF3-47A7-8524-C8C6FE4B26FA/alfred-workflow-todoist.js:1:3421)
    at N ([snip]/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A552C27-FCF3-47A7-8524-C8C6FE4B26FA/alfred-workflow-todoist.js:1:3539)
    at [snip]/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A552C27-FCF3-47A7-8524-C8C6FE4B26FA/alfred-workflow-todoist.js:29:367514
    at Object.<anonymous> (/[snip]/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3A552C27-FCF3-47A7-8524-C8C6FE4B26FA/alfred-workflow-todoist.js:29:367586)

**Comment by moranje** [comment]
It is supposed to work in `alpha.9` and should not throw an error. Thanks for reporting, did you change the filter settings? I'll see what I can find.

Martien

**Comment by wesleylancel** [comment]
Hi Martien,

I didn't change any settings in the workflow.

Double quotes & dollars are checked in the block, backquotes and backslashes are not. Enabling them doesn't solve the problem though.

- Wesley

**Comment by moranje** [comment]
I've figured it out, the plist is outdated. I'll put a fix out shortly. Thanks for reporting.

**Comment by moranje** [comment]
Let me know if `alpha.10` fixes this for you.

**Comment by wesleylancel** [comment]
Just updated and it work! Thanks!

**Comment by moranje** [comment]
Great, thanks for reporting
