### ISSUE TITLE
Feature Request: Assign item to Project

### ISSUE THREAD

**Issue by douglance** [moranje/alfred-workflow-todoist#2]
I'm back! :smile: 

It would be great to be able to assign a task to a certain project using the comma separator syntax. I am adding tasks and then going through my inbox later to sort them to my different projects. It would save me the hassle. 

Thanks again for the great workflow! :+1:

**Comment by moranje** [comment]
Hi!

Sorry for the late reply, I am currently stretched a little thin for time. I'll pick this up later but I don't expect to have a lot of time to dedicate to this in the next couple of weeks. I'll check back with you in a little bit.

Martien

**Comment by moranje** [comment]
In case you hadn't noticed, Todoist now natively supports this.

Martien

**Comment by noisufnoc** [comment]
Hi Martien, can you point me to the docs/syntax for the native support in Todoist?

**Comment by moranje** [comment]
Yes, with the app in the background run `shift` + `cmd` + `a`. There you'll be able to use all todoists natural language features. Like '#' for selecting projects, '+' for selecting a person etc.

**Comment by moranje** [comment]
This was implemented on the last update
