### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by BenCole** [moranje/alfred-workflow-todoist#21]
Setting this workflow up on a new machine and unable to add the api token.

t:status {{api token}}

This error "not a valid token" is returned.

The string passes the regex check but errors afterwards.

It looks like there are some other users seeing this behaviour in the last couple of weeks: https://www.alfredforum.com/topic/8554-todoist-workflow/?page=3

**Comment by moranje** [comment]
You are right. Thanks for creating an issue. I updated the workflow to version 3.1.6 which fixes that problem. It had to do with JSON not being parsed correctly, which messed up the way token was checked.

Martien

**Comment by BenCole** [comment]
@moranje Thanks for update. Unfortunately there seems to be a second issue when creating todos. I now get an "invalid argument" error message when attempting to create a simple todo. It looks like someone on the forum has the same issue too.

https://www.alfredforum.com/topic/8554-todoist-workflow/?do=findComment&comment=53620
