### ISSUE TITLE
terminal-notifier not trusted

### ISSUE THREAD

**Issue by single-stop-rj** [moranje/alfred-workflow-todoist#215]
I recently installed - and when i go to ender a TODO into alfred, I get a MacOS error stating that terminal-notifier has been recently installed and is not trusted. i did a search for it, and there are actually 8 terminal-notifier apps in my system ( I am assuming from other software ) 

How do I correct this issue?

**Comment by functionalStoic** [comment]
Hi @single-stop-rj,
I ran into this as well. After receiving the message:
- open up the Security & Privacy section of System Preferences
- Unlock if necessary
- allow terminal notifier when the message shows up at the bottom
- Then try again

Hope that helps!

**Comment by DevanFischer** [comment]
A second solution for anyone who cannot see the message in System Preferences as @functionalStoic suggested is:
 
1. Go to the workflow in Alfred Preferences
2. Right click on the Todoist workflow
3. Select open in Finder
![image](https://user-images.githubusercontent.com/25752779/141202333-b2c0d714-91ed-41c9-9351-c50da95a8e5e.png)
4. Open the notifier folder within the workflow folder
![image](https://user-images.githubusercontent.com/25752779/141202485-fe21401e-3047-4a45-ac7d-ec079802f54e.png)
5. Right click on terminal-notifier and select Open
![image](https://user-images.githubusercontent.com/25752779/141202587-f3de2181-6fa3-4d4d-a88e-7da45b2064d3.png)

This will present a dialogue box asking if you want to open the application. 
Select Open and you can now run the workflow.
Hope this helpful for anyone who encounters this issue.

**Comment by moranje** [comment]
Thanks 🙏
