### ISSUE TITLE
Binary seems to be outdated

### ISSUE THREAD

**Issue by idpaterson** [moranje/alfred-workflow-todoist#25]
I forked the repo to submit a pull request increasing the maximum characters for matching projects and tags from 3 to unlimited, only to realize that you had already made that change. The binary on master seems to be for an older version that is still parsing tasks in JS; the new shell scripts (which for the purpose of my tweak already use `[^ ,]*` rather than `[^ ,]{0,3}`) are not bundled.

I'm grateful for this workflow since the Todoist Quick Add feature can be horribly slow and it's a very easy transition from my Wunderlist workflow.

**Comment by moranje** [comment]
Yeah, I'm sorry about that. I'm working through a rewrite until then I won't be updating much. I've basically rewritten the entire thing.

**Comment by disrupted** [comment]
Can you let me know here when you've finished the rewrite? Would be highly appreciated :)

**Comment by moranje** [comment]
Yeah will do!

Op za 2 dec. 2017 20:39 schreef disrupted <notifications@github.com>:

**Comment by idpaterson** [comment]
That's great, thanks for the news.

**Comment by alectivism** [comment]
Also experiencing this – looking forward to trying out the updated version! Thanks :)
