### ISSUE TITLE
Todoist API error, invalid temp_id

### ISSUE THREAD

**Issue by idpaterson** [moranje/alfred-workflow-todoist#27]
The Todoist API has started returning a 400 error when adding a task:
> Invalid argument value ({"threshold":1,"expected":"minlen","argument":"temp_id"})

Please update the published version of the workflow to generate a uuid for `temp_id` rather than sending a blank string. Users facing this glitch can edit line 214 of `js/todoist.js` in the workflow to replace the blank string with `utilities_1.uuid()`:
```diff
- temp_id: '',
+ temp_id: utilities_1.uuid(),
```

The purpose of the `temp_id` in Todoist API calls is to allow objects to cross-reference other objects that are being created in the same request, and to provide a mechanism for mapping creation of multiple new objects to the proper final IDs. The workflow does not need this mapping but it seems the `temp_id` must be provided with a valid value regardless.

**Comment by moranje** [comment]
Closing until the new version is released
