### ISSUE TITLE
Workflow does not honour Alfreds and macOS proxy settings

### ISSUE THREAD

**Issue by snipem** [moranje/alfred-workflow-todoist#29]
When adding a todo task with "todo test" I get the following error:

```
[2018-01-27 00:14:06][utility.junction] Processing output of 'utility.filter' with arg 'Error: getaddrinfo ENOTFOUND todoist.com todoist.com:443
Error: getaddrinfo ENOTFOUND todoist.com todoist.com:443
Error: getaddrinfo ENOTFOUND todoist.com todoist.com:443
```

My Mac does not have a direct route to the internet. Adding tasks works when having a direct route.

Alfred-workflow-todoist version: v4.0.2
Alfred version: v.3.5.1

**Comment by moranje** [comment]
Not sure what you were asking here, closing. I can reopen if this (whatever this is) remains an issue.
