### ISSUE TITLE
listing todos not functional

### ISSUE THREAD

**Issue by jdoconnor** [moranje/alfred-workflow-todoist#3]
I'm getting a file not found... when i have time, i'll dig into this, but I wanted to leave a note here with the debug information.

This happens when typing "tod" and using the mouse or keyboard to select the list todos item

```
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 340:377: execution error: Error on line 15: Error: File wasn't found. (-43)
```

**Comment by moranje** [comment]
I see, can you verify that there is a called `~/Library/Script\ Libraries/` containing three files?

**Comment by jdoconnor** [comment]
I manually copied them into that directory, but still error on reading the file (the permissions are ok)
`[ERROR: alfred.workflow.input.scriptfilter] Code 1: 340:377: execution error: Error on line 15: Error: Library can't be loaded at path: /Users/jdoc/Library/Script Libraries/workflow.scpt. (-2700)`

```
ls -lah "/Users/jdoc/Library/Script Libraries/workflow.scpt"
-rwxr-xr-x@ 1 jdoc  staff   1.4K Mar 13 08:06 /Users/jdoc/Library/Script Libraries/workflow.scpt
```

weird, huh?

**Comment by moranje** [comment]
Yeah, the debugger on OSX javascript is not very descriptive. 

For reference this is the problem:
line 15 in get-tasks.js
```js
var workflow = Library( 'workflow' ),
```

However it makes no sense to me that this does't work. Are you on El Cap?

**Comment by jdoconnor** [comment]
I am. zsh as default (maybe I'll throw it into bash and see if that's
better)

**Comment by noisufnoc** [comment]
I'm having a similar issue, on OSX 10.10

`[ERROR: alfred.workflow.input.scriptfilter] Code 1: 2016-04-12 16:47:25.338 osascript[61776:4342188] warning: failed to get scripting definition from /usr/bin/osascript; it may not be scriptable.
2016-04-12 16:47:25.377 osascript[61776:4342188] warning: failed to get scripting definition from /Users/noisufnoc/Library/Script Libraries/workflow.scpt; it may not be scriptable.
2016-04-12 16:47:25.387 osascript[61776:4342188] warning: failed to get scripting definition from /Users/noisufnoc/Library/Script Libraries/todoist.scpt; it may not be scriptable.
412:480: execution error: Error on line 17: Error: Script error. (-1753)`

I had to manually copy the scripts to ~/Library/Script Libraries

**Comment by moranje** [comment]
I will look into a better solution for this

**Comment by moranje** [comment]
I will try to find some time for this soon, more people seem to be using this than I thought.

Martien

**Comment by moranje** [comment]
Updated to version 2.0.0, listing requires Node.js and should now work,

Cheers
