### ISSUE TITLE
Time string doesn't work.

### ISSUE THREAD

**Issue by cbiggins** [moranje/alfred-workflow-todoist#32]
Using the todoist time strings doesn't work for me. See images below of creating the task and viewing it in Todoist. 

![screen shot 2018-07-05 at 1 04 32 pm](https://user-images.githubusercontent.com/30534/42300473-0f0a97ea-8054-11e8-8fb0-70335e679a15.jpg)

![screen shot 2018-07-05 at 1 04 48 pm](https://user-images.githubusercontent.com/30534/42300472-0edd6a86-8054-11e8-864d-9e147f729ecc.jpg)

Any help would be much appreciated. Thanks for this workflow!

**Comment by DariuszMusielak** [comment]
For me it works in that way,
> `todo my task, tomorrow, #work`

**Comment by cbiggins** [comment]
Perfect! Thank you!
