### ISSUE TITLE
Priority orders

### ISSUE THREAD

**Issue by melikarslan** [moranje/alfred-workflow-todoist#33]
First of all thank you for great work.

In Alfred workflow, the most important priority can be set as !!4, but this is not the correct notion according to default Todoist shortcuts. It should be !!1. 

You can see details on https://support.todoist.com/hc/en-us/articles/205873321

> You can give your tasks one of four priority levels – 1 being the most important (marked as red) and 4 being everything else (no color).

Also, it would be great to support p1,p2,p3,p4 notion like Todoist.

**Comment by moranje** [comment]
I'm adressing this in an update
