### ISSUE TITLE
Listing doesn't work

### ISSUE THREAD

**Issue by raidiant** [moranje/alfred-workflow-todoist#4]
I have listing items bound to Alt+t, but it says it's retrieving my Todos and then shows nothing at all.

**Comment by twhite96** [comment]
Same issue here.

**Comment by JC1738** [comment]
Yes, using Alfred 3, adding works, but retrieving list doesn't do anything.  The add in task is great, thanks!

**Comment by moranje** [comment]
I will try to find some time for this soon, thanks for letting me know

**Comment by moranje** [comment]
Updated to version 2.0.0, listing requires Node.js and should now work,

Cheers
