### ISSUE TITLE
Error with self-signed certificate

### ISSUE THREAD

**Issue by smithers420** [moranje/alfred-workflow-todoist#43]
After setting up the API token (issued by Todoist) I cannot get the workflow to work anymore. See error attached. Any idea how to restore this?
![2018-10-11_16-05-24](https://user-images.githubusercontent.com/44062422/46809948-e57c6980-cd6f-11e8-91ec-a6b28692f393.png)

**Comment by moranje** [comment]
This really sounds like a todoist problem. I have no way to influence SSL certificates. Does anyone else experience this?

**Comment by smithers420** [comment]
It seemed like it was caused by the company's network I was on yesterday. Probably they are replacing certificates by the firewall, etc. caused this issue with Todoist. Today it is working fine again. Closing this issue! Thanks. Awesome workflow by the way! kudos.
