### ISSUE TITLE
Due date not working in french

### ISSUE THREAD

**Issue by mamembrado** [moranje/alfred-workflow-todoist#46]
### Describe the bug

When trying to create a new task with a due date, everything is working fine (@, #, p, text, etc...) except the due date. I'm using todoist in french and have configured the workflow in fr too 
 
### Steps to reproduce

1. Alfred input 'todo test2 à faire demain 14h00 !!1 @plan  #Personnel ' Translate to '
todo test2 to do tomorrow 14:00 !!1 @plan #Personnel' (same issue with 24/10/2018 or 10/24/2018 or 24/10 or samedi (Saturday))
2. Press enter
3. See Alfred todoist WF notification saying that the task has been created 
4. The task in todoist has been created but the due date hasn't been detected and set, it's still in the title 

### Expected behavior

Was expecting to have a new task with a due date set to tomorrow 14h00

**Comment by moranje** [comment]
Check out this bit of the [documentation](https://github.com/moranje/alfred-workflow-todoist#create-task)

The reason for this is that date and time parsing isn't something I want to support (it would mean I would have to parse all the different time strings and date string in all languages Todoist supports). But todoist can very well. So I just need to know where the date-time string starts and ends, hence the `,`

try `todo test2 à faire demain !!1 @plan #Personnel, 14h00`

Martien
