### ISSUE TITLE
todos query +  return deletes task instead of complete it

### ISSUE THREAD

**Issue by toyflish** [moranje/alfred-workflow-todoist#47]
A queried task gets deleted but feedback is "task completed"
 
### Steps to reproduce

1. Alfred input 'todos email'
2. Click on 'email task'
3. message pops up "task completed" but if you look in the webinterface you find the task under deleted tasks

### Expected behavior
Task should be under completed task to receive Karma-points

**Comment by moranje** [comment]
See if the update tickles your fancy. @toyflish

**Comment by toyflish** [comment]
perfect, you saved my karma ;)
