### ISSUE TITLE
cannot find projects

### ISSUE THREAD

**Issue by shigg1120** [moranje/alfred-workflow-todoist#49]
I created the project `Fitness` on the OS app. When I create a task with the workflow it does not show the project created.
![image](https://user-images.githubusercontent.com/15307586/47703011-1f030f00-dc62-11e8-9524-18af48615f3e.png)

![image](https://user-images.githubusercontent.com/15307586/47703055-49ed6300-dc62-11e8-9464-66aca507787f.png)

**Comment by moranje** [comment]
Cache is refreshed every hour by default. It's something that's adjustable in settings.

Martien
