### ISSUE TITLE
Issue: Task is not persisting to todoist after submit

### ISSUE THREAD

**Issue by tconroy** [moranje/alfred-workflow-todoist#5]
Hi, 
I'm running into an issue with this workflow. I've followed the setup instructions (minus installing NodeJS, since I already have that installed as I am a web developer). 

When I open Alfred and type `todo pickup the milk tomorrow @ 9am`, hit enter, I get the OSX notification that the task was saved. However, when I open my todoist app or check my account online, the task is not there.

Any ideas what may be causing this issue? I tried re-issuing an API key to see if that would work, but it did not help.

I am a Premium user of Todoist, and have the Alfred PowerPack, if that helps at all.

OSX Version: 10.11.5
Alfred version: 3.0..3
Todoist version:  813
Node version: 5.5.0

Cheers

**Comment by tconroy** [comment]
aha! so I seem to have found the solution.

The workflow did not create a directory in 
```
/Application Support/Alfred 3/Workflow Data/com.alfred-workflow-todoist`
```

so I manually created the `com.alfred-workflow-todoist` folder in that directory.

After doing that, I re-added my API token `t:token <my token here>`

that seems to have created the `settings.json` file in the `com.alfred-workflow-todoist` directory. My todos are now getting added to todoist. :) 


Might want to throw this info into the readme as I've noticed several other users have run across a similar issue!

**Comment by bodegabodega** [comment]
Thanks for the heads up @tconroy .. and thanks for the workflow @moranje

**Comment by moranje** [comment]
I've fixed that now, thanks for the heads up!

**Comment by tconroy** [comment]
👍
