### ISSUE TITLE
Node binary not found when using NVM

### ISSUE THREAD

**Issue by beedaan** [moranje/alfred-workflow-todoist#61]
### Describe the bug

Cannot configure workflow

### Steps to reproduce

1. Alfred input 'todo:setting'
2. See error

### Expected behavior

I expect to see the list of settings I can configure, like `token`, but instead I get the default Alfred action menu to "Search Google for 'todo:setting'

### Error logs

Paste error log below (STEPS: 1. Open workflows tab in Alfred 2. Select `Alfred Workflow Todoist` 3. Select `Toggle debugging mode` in de upper right corner 4. Set logging to `All information` 5. Rerun query)

Log:

```
[2018-12-11 09:03:13][ERROR: input.scriptfilter] Code 127: /bin/bash: line 11: node: command not found
```

### Additional context

I use zsh instead of bash, so my bash is not set up with my node environment.  I realize this is a problem.  Maybe it's worth adding a note, or a configuration option?

**Comment by moranje** [comment]
Just to make sure, have you installed node (as mentioned [here](https://github.com/moranje/alfred-workflow-todoist#getting-started))?

**Comment by beedaan** [comment]
I have node installed
```
~ ➤ echo $SHELL
/bin/zsh
~ ➤ node -v
v10.8.0
~ ➤ which node
/Users/<username>/.dotfiles/node/nvm/versions/node/v10.8.0/bin/node
```

**Comment by moranje** [comment]
There's your problem, you've installed node in a non-standard location. I add the default node to your `PATH=$PATH:/usr/local/bin:/usr/bin`. But that means your node binary isn't found. Open the alfred workflow and add it to the scripts or move the binary to a default location. The latter is preferable since you'de need to update them with each upgrade. 

I use zshell myself but the Alfred scripts are run in isolation (none of the system settings are taken into account) that's why I need to redefine PATH at all.

**Comment by moranje** [comment]
Another thing you could do is install `npm install -g nave` and use it's `nave usemain stable` or `nave usemain <version>` to create a global binary in the default location.

**Comment by beedaan** [comment]
Thank you for the thoughtful feedback.  I really appreciate it.

I would rather not install a system version of node because I use [nvm](https://github.com/creationix/nvm) to manage my node environment.  I also would rather not use nave because it duplicates a lot of the functionality of nvm.

I use other software that depends on node to run tasks such as IntelliJ IDEA.  The way JetBrains handle this type of situation is by allowing the user to specify the node runtime.  Do you think that would be a possible feature?

**Comment by moranje** [comment]
That's not that easy I'm afraid. You'd have implement it all in bash, which is something I have made a point of not doing anymore. However, I think the solution is fairly simple. A `node` symlink in `/usr/bin` to the active binary (`/Users/<username>/.dotfiles/node/nvm/versions/node/v10.8.0/bin/node`) should fix the problem, right?

**Comment by beedaan** [comment]
That would fix the problem with this specific issue, but it would cause
other issues with my environment.  I would be locking myself to a specific
version of node.  I have multiple projects on my machine that use different
versions of node, which is one of the reasons I use nvm.

**Comment by moranje** [comment]
Closing as there is no real solution here.
