### ISSUE TITLE
Any way to disable fuzzy search?

### ISSUE THREAD

**Issue by imusmanr** [moranje/alfred-workflow-todoist#72]
Hi there,

First of all, thank you so much for building this awesome utility. It's great for adding new tasks easily directly from Alfred.

However, in it's current form, I find that "fuzzy" search makes the search quite unusable, since it returns pages and pages of endless tasks that have nothing to do with my search term. 

I am not sure if this feature already exists and maybe I'm just not using it right, but it would be nice if there was a way to search exact query terms rather than an always-on fuzzy search. 

Let me know if something is unclear, and I can provide more details.

Thanks again!
-Usman

**Comment by moranje** [comment]
So you are saying that if you type in the exact task query you are not getting the task you are looking for?

**Comment by imusmanr** [comment]
Maybe you can see what I mean in this picture:

I searched for just a simple "condo" phrase using the workflow, I see TONS and TONS of results (look at size of scroll wheel):
<img width="571" alt="screen shot 2019-01-01 at 9 49 15 pm" src="https://user-images.githubusercontent.com/9157460/50581505-28018f80-0e0f-11e9-91ae-8071f6b486da.png">

If I search for that in Todoist, I get only 2 results, which exactly contain the word "Condo":
<img width="652" alt="screen shot 2019-01-01 at 9 50 33 pm" src="https://user-images.githubusercontent.com/9157460/50581538-6d25c180-0e0f-11e9-80dd-70a57d29528e.png">

It would be nice to have that feature through this Alfred workflow - exact search (with an option for fuzziness).

**Comment by moranje** [comment]
I see, that's no exact match though. The algorithm you are describing is (for the lack of better terminology) a word bounded partial string matching algorithm. I did a quick search for a library that does matching that way but I haven't found anything that does what you want it to do.

I would be willing to switch algorithm to have more sensible defaults if there is a better library available.

**Comment by moranje** [comment]
### Note to self

Maybe this could work:

https://github.com/nextapps-de/flexsearch

**Comment by moranje** [comment]
Closing this for now. Fuzzy matching is baked deeply into the workflow. For now the benefit of easy and fast results outweighs the disadvantage of having fewer exact results. Feel free to disagree, I'm willing to change my view if enough people do so.
